name: Generate tools.json

on:
  push:
    branches: [ main, work ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Generate tools.json
        run: node generate-tools.js
      - name: Commit tools.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tools.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update tools.json"
            git push
          fi
